@startuml
title RsNano Crates Overview

[types]
[work]
[utils]
[ledger]
[store_lmdb]
[messages]
[network]
[network_protocol]
[daemon]
[node]
[main]
[wallet]

node "rpc"{
[rpc_messages]
[rpc_server]
[rpc_client]
}

node "websocket"{
[websocket_messages]
[websocket_server]
[websocket_client]
}

node "nullables" {
[fs]
[clock]
[random]
[tcp]
[lmdb]
[http_client]
[console]
[env]
[output_tracker]
}

[main] --> [daemon]
[daemon] --> [node]
[daemon] --> [rpc_server]
[daemon] --> [websocket_server]
[rpc_server] --> [node]
[rpc_server] --> [rpc_messages]
[rpc_client] --> [rpc_messages]
[rpc_messages] --> [types]
[node] --> [ledger]
[node] --> [network_protocol]
[node] --> [wallet]
[network_protocol] --> messages
[network_protocol] --> network
[websocket_server] --> [websocket_messages]
[websocket_server] --> [node]
[websocket_messages] --> [types]
[websocket_client] --> [websocket_messages]
[messages] --> [work]
[messages] --> [utils]
[network] --> [utils]
[ledger] --> [store_lmdb]
[ledger] --> [work]
[ledger] --> [utils]
[store_lmdb] --> [types]
[work] --> [types]
[work] --> [utils]
[wallet] --> [ledger]
[types] -[hidden]-> "nullables"
@enduml
